# Generated by Django 4.0.6 on 2022-07-19 10:08

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('surname', models.CharField(max_length=256, verbose_name='Surname')),
                ('username', models.CharField(max_length=256, null=True, unique=True, verbose_name='Username')),
                ('age', models.PositiveIntegerField(null=True, verbose_name='Age')),
                ('phone', models.CharField(max_length=128, verbose_name='Phone')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='user-images/', verbose_name='Image')),
                ('gender', models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], max_length=128, verbose_name='Gender')),
                ('address', models.CharField(choices=[('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Samarqand', 'Samarqand'), ('Tashkent', 'Tashkent'), ('Jizzax', 'Jizzax'), ('Surxondaryo', 'Surxondaryo'), ('Navoiy', 'Navoiy'), ('Xorazm', 'Xorazm'), ('Qashqadaryo', 'Qashqadaryo'), ('Buxoro', 'Buxoro'), ('Sirdaryo', 'Sirdaryo'), ('Fargona', 'Fargona')], max_length=128, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
