# Generated by Django 4.0.6 on 2022-07-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_view',
            new_name='is_ban',
        ),
    ]
