# Generated by Django 4.0.6 on 2022-07-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_is_view_book_is_ban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
