# Generated by Django 4.1.1 on 2022-09-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_ban',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_checked',
        ),
    ]
